const fs = require('fs');
const path = require('path');

const productsPath = path.join(__dirname, '..', 'src', 'data', 'products.json');
const products = JSON.parse(fs.readFileSync(productsPath, 'utf8'));

const newGames = [
  {
    sku: "GBA-001",
    slug: "gba-001-pokemon-emerald",
    name: "Pok\u00e9mon Emerald",
    platform: "Game Boy Advance",
    category: "Games > GBA",
    genre: "RPG",
    price: 85,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Emerald voor de Game Boy Advance \u2014 de ultieme versie van de Hoenn-regio. Vang zowel Kyogre als Groudon, daag de Battle Frontier uit en ontdek exclusieve verhaallijnen. Met verbeterde animaties en de mogelijkheid om Pok\u00e9mon uit Ruby, Sapphire, FireRed en LeafGreen te verhandelen. Een van de meest geliefde Pok\u00e9mon games ooit gemaakt. Losse cartridge, getest en werkend.",
    weight: 0.05,
    isConsole: false,
    isPremium: true,
    image: "/images/products/gba-001-pokemon-emerald.webp",
    backImage: "/images/products/gba-001-pokemon-emerald-back.webp",
    inkoopPrijs: 34,
    inkoopFeatured: true
  },
  {
    sku: "GBA-002",
    slug: "gba-002-pokemon-ruby",
    name: "Pok\u00e9mon Ruby",
    platform: "Game Boy Advance",
    category: "Games > GBA",
    genre: "RPG",
    price: 40,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Ruby voor de Game Boy Advance \u2014 verken de tropische Hoenn-regio en vang het legendarische Groudon. Met 135 nieuwe Pok\u00e9mon, dubbelgevechten en Pok\u00e9mon wedstrijden. Bouw je eigen geheime basis en handel met vrienden via de Link Cable. Een klassieker uit generatie 3. Losse cartridge, getest en werkend.",
    weight: 0.05,
    isConsole: false,
    isPremium: false,
    image: "/images/products/gba-002-pokemon-ruby.webp",
    backImage: "/images/products/gba-002-pokemon-ruby-back.webp",
    inkoopPrijs: 16,
    inkoopFeatured: true
  },
  {
    sku: "GBA-003",
    slug: "gba-003-pokemon-firered",
    name: "Pok\u00e9mon FireRed",
    platform: "Game Boy Advance",
    category: "Games > GBA",
    genre: "RPG",
    price: 65,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon FireRed voor de Game Boy Advance \u2014 de vernieuwde remake van het originele Pok\u00e9mon Red. Herbeleef het avontuur door Kanto met verbeterde graphics, nieuwe gebieden zoals de Sevii Islands en de mogelijkheid om te handelen met Ruby, Sapphire en Emerald. Losse cartridge, getest en werkend.",
    weight: 0.05,
    isConsole: false,
    isPremium: true,
    image: "/images/products/gba-003-pokemon-firered.webp",
    backImage: "/images/products/gba-003-pokemon-firered-back.webp",
    inkoopPrijs: 26,
    inkoopFeatured: true
  },
  {
    sku: "GBA-004",
    slug: "gba-004-pokemon-leafgreen",
    name: "Pok\u00e9mon LeafGreen",
    platform: "Game Boy Advance",
    category: "Games > GBA",
    genre: "RPG",
    price: 60,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon LeafGreen voor de Game Boy Advance \u2014 de vernieuwde remake van Pok\u00e9mon Green/Blue. Verken de Kanto-regio met prachtige GBA-graphics en ontdek de Sevii Islands. Vang exclusieve Pok\u00e9mon die niet in FireRed zitten. Losse cartridge, getest en werkend.",
    weight: 0.05,
    isConsole: false,
    isPremium: true,
    image: "/images/products/gba-004-pokemon-leafgreen.webp",
    backImage: "/images/products/gba-004-pokemon-leafgreen-back.webp",
    inkoopPrijs: 24,
    inkoopFeatured: true
  },
  {
    sku: "GBA-005",
    slug: "gba-005-pokemon-sapphire",
    name: "Pok\u00e9mon Sapphire",
    platform: "Game Boy Advance",
    category: "Games > GBA",
    genre: "RPG",
    price: 40,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Sapphire voor de Game Boy Advance \u2014 verken de Hoenn-regio en vang het legendarische Kyogre. Met 135 nieuwe Pok\u00e9mon, dubbelgevechten en Pok\u00e9mon wedstrijden. De tegenhanger van Ruby met exclusieve Pok\u00e9mon en een unieke verhaallijn rond Team Aqua. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.05,
    isConsole: false,
    isPremium: false,
    image: "/images/products/gba-005-pokemon-sapphire.webp",
    backImage: "/images/products/gba-005-pokemon-sapphire-back.webp",
    inkoopPrijs: 16,
    inkoopFeatured: true
  },
  {
    sku: "DS-001",
    slug: "ds-001-pokemon-soulsilver",
    name: "Pok\u00e9mon SoulSilver",
    platform: "Nintendo DS",
    category: "Games > DS",
    genre: "RPG",
    price: 90,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon SoulSilver voor de Nintendo DS \u2014 de geliefde remake van Pok\u00e9mon Silver. Verken zowel Johto als Kanto met verbeterde DS-graphics. Je eerste Pok\u00e9mon loopt achter je aan op het bovenste scherm. Een van de hoogst gewaardeerde Pok\u00e9mon games ooit. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.08,
    isConsole: false,
    isPremium: true,
    image: "/images/products/ds-001-pokemon-soulsilver.webp",
    backImage: "/images/products/ds-001-pokemon-soulsilver-back.webp",
    inkoopPrijs: 36,
    inkoopFeatured: true
  },
  {
    sku: "DS-002",
    slug: "ds-002-pokemon-pearl",
    name: "Pok\u00e9mon Pearl",
    platform: "Nintendo DS",
    category: "Games > DS",
    genre: "RPG",
    price: 30,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Pearl voor de Nintendo DS \u2014 ontdek de Sinnoh-regio en vang het legendarische Palkia. De vierde generatie Pok\u00e9mon met online handelen, de Underground en Pok\u00e9mon wedstrijden. Losse cartridge, getest en werkend.",
    weight: 0.08,
    isConsole: false,
    isPremium: false,
    image: "/images/products/ds-002-pokemon-pearl.webp",
    backImage: "/images/products/ds-002-pokemon-pearl-back.webp",
    inkoopPrijs: 12,
    inkoopFeatured: false
  },
  {
    sku: "DS-003",
    slug: "ds-003-pokemon-black",
    name: "Pok\u00e9mon Black",
    platform: "Nintendo DS",
    category: "Games > DS",
    genre: "RPG",
    price: 45,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Black voor de Nintendo DS \u2014 ontdek de Unova-regio ge\u00efnspireerd door New York City. Met 156 compleet nieuwe Pok\u00e9mon en een dieper verhaal dan ooit tevoren. Exclusief voor Black: Reshiram en Black City. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.08,
    isConsole: false,
    isPremium: false,
    image: "/images/products/ds-003-pokemon-black.webp",
    backImage: "/images/products/ds-003-pokemon-black-back.webp",
    inkoopPrijs: 18,
    inkoopFeatured: true
  },
  {
    sku: "DS-004",
    slug: "ds-004-pokemon-white",
    name: "Pok\u00e9mon White",
    platform: "Nintendo DS",
    category: "Games > DS",
    genre: "RPG",
    price: 45,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon White voor de Nintendo DS \u2014 de tegenhanger van Black in de Unova-regio. Exclusief voor White: Zekrom en White Forest. Met 156 nieuwe Pok\u00e9mon, Triple Battles en Rotation Battles. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.08,
    isConsole: false,
    isPremium: false,
    image: "/images/products/ds-004-pokemon-white.webp",
    backImage: "/images/products/ds-004-pokemon-white-back.webp",
    inkoopPrijs: 18,
    inkoopFeatured: true
  },
  {
    sku: "GB-001",
    slug: "gb-001-pokemon-red",
    name: "Pok\u00e9mon Red",
    platform: "Game Boy / Color",
    category: "Games > Game Boy",
    genre: "RPG",
    price: 35,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Red voor de originele Game Boy \u2014 waar het allemaal begon. Vang alle 151 originele Pok\u00e9mon, versla de acht Gym Leaders en word de Pok\u00e9mon Kampioen. De game die een wereldwijd fenomeen startte. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.05,
    isConsole: false,
    isPremium: false,
    image: "/images/products/gb-001-pokemon-red.webp",
    backImage: "/images/products/gb-001-pokemon-red-back.webp",
    inkoopPrijs: 14,
    inkoopFeatured: true
  },
  {
    sku: "3DS-001",
    slug: "3ds-001-pokemon-x",
    name: "Pok\u00e9mon X",
    platform: "Nintendo 3DS",
    category: "Games > 3DS",
    genre: "RPG",
    price: 30,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon X voor de Nintendo 3DS \u2014 de eerste volledig 3D Pok\u00e9mon hoofdgame. Verken de Kalos-regio ge\u00efnspireerd door Frankrijk, ontdek Mega Evoluties en het nieuwe Fairy-type. Inclusief het legendarische Xerneas. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.08,
    isConsole: false,
    isPremium: false,
    image: "/images/products/3ds-001-pokemon-x.webp",
    backImage: "/images/products/3ds-001-pokemon-x-back.webp",
    inkoopPrijs: 12,
    inkoopFeatured: false
  },
  {
    sku: "3DS-002",
    slug: "3ds-002-pokemon-omega-ruby",
    name: "Pok\u00e9mon Omega Ruby",
    platform: "Nintendo 3DS",
    category: "Games > 3DS",
    genre: "RPG",
    price: 35,
    condition: "Gebruikt",
    completeness: "Losse cartridge",
    type: "simple",
    description: "Pok\u00e9mon Omega Ruby voor de Nintendo 3DS \u2014 de prachtige 3D-remake van het klassieke Pok\u00e9mon Ruby. Herbeleef de Hoenn-regio met volledig vernieuwde graphics, Mega Evoluties en Primal Reversion voor Groudon. Losse cartridge, getest en werkend. Europese versie (PAL/EUR).",
    weight: 0.08,
    isConsole: false,
    isPremium: false,
    image: "/images/products/3ds-002-pokemon-omega-ruby.webp",
    backImage: "/images/products/3ds-002-pokemon-omega-ruby-back.webp",
    inkoopPrijs: 14,
    inkoopFeatured: false
  }
];

const allProducts = [...products, ...newGames];
fs.writeFileSync(productsPath, JSON.stringify(allProducts, null, 2));

console.log('Producten bijgewerkt:', allProducts.length, 'totaal');
console.log('Nieuw toegevoegd:', newGames.length, 'Pokemon games');
console.log('');
newGames.forEach(g => console.log(' ', g.sku, '-', g.name, '-', g.platform, '- \u20ac' + g.price));
